# Generated by Django 4.1.1 on 2022-09-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="Year_of_published",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
