# Generated by Django 4.1.1 on 2022-09-23 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_author_user_is_seller"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_author",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_seller",
        ),
    ]
