# Generated by Django 4.1.1 on 2022-09-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_is_author_remove_user_is_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.CharField(
                choices=[("author", "Author"), ("seller", "Seller")],
                default="seller",
                max_length=10,
            ),
        ),
    ]
