# Generated by Django 4.1.1 on 2022-09-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=models.CharField(
                choices=[("seller", "Seller"), ("author", "Author")],
                default="seller",
                max_length=10,
            ),
        ),
    ]
