# Generated by Django 4.1.1 on 2022-09-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_books_remove_user_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="Cost",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="books",
            name="visibility",
            field=models.BooleanField(default=True),
        ),
    ]
