# Generated by Django 4.1.1 on 2022-09-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_books_cost_books_visibility"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Books",
        ),
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=models.CharField(
                choices=[("seller", "Seller"), ("author", "Author")],
                default="seller",
                max_length=10,
            ),
        ),
    ]
